Repository FredrikHj/projekt_-AgilScrum, pull requests merged in 2020-01, with the labels that each got.

#64 Feature test gamelist
  jest.setup3.js
  package.json
  src/testF/test.test.js
Labels: test

#69 change css in landing page to match the rest of the pages
  package.json
  src/App.css
  src/components/pages/startPage.js
Labels: frontend

#73 Test chessboard
  src/testF/test.test.js
Labels: test

#74 Feature gamelist ifsamename
  src/components/GameCreation/GameCreation.js
  src/components/GameList/GameList.js
  src/components/localStorage.js
  src/components/pages/startPage.js
Labels: frontend

#82 hotfix, move number in correct order
  src/components/HistoryList/HistoryList.js
Labels: bug
